default_config: coa_test
configs:
  coa_test:
    document: coa
    debug: False
    run:
      limit: 0
      max_attempts: 1
      print_cache: False
      save_cache: True
      refresh_cache: True
    rpa:
      download_timeout: 3
    batch_source:
      type: CSVBatchSource
      path: test_data.csv
    cache:
      type: LocalCache
      path: "temp/test/coa.pk"
    document_path: "temp/test/coa"
    schedule:
      enabled: true
      cron: "0-59/2 * * * * America/Los_Angeles"
      polling_interval: 60
      allow_failures: 0
    log:
      file: True
      file_path: "logs/test/coa.log"
      file_level: "DEBUG"
      console: True
      console_level: "DEBUG"
  coa_prod:
    document: coa
    debug: False
    run:
      limit: 5
      max_attempts: 0
      print_cache: False
      save_cache: True
      refresh_cache: True
    rpa:
      download_timeout: 3
    batch_source:
      type: SQLBatchSource
      tenant: "{{env_var('XAAzTenant')}}"
      server: "{{ env_var('XASynapseOnDemandUrl') }}"
      database: "d365_financeops"
      secret:
        type: keyring
        url: az
        user: "2f0bd0f3-2690-49a2-80d0-da506522ab70"
    cache:
      type: LocalCache
      path: "temp/prod/coa.pk"
    document_path: "temp/prod/coa"
    schedule:
      enabled: true
      cron: "25 7-16/3 * * 1-5 America/Los_Angeles"
      polling_interval: 60
      allow_failures: 0
    log:
      file: True
      file_path: "logs/prod/coa.log"
      file_level: "WARNING"
      console: True
      console_level: "DEBUG"



